ALTER SESSION SET CONTAINER=FREEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER safy_seed_owner IDENTIFIED BY "Oracle_owner_database_services_fake_123"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO safy_seed_owner;
ALTER USER safy_seed_owner QUOTA UNLIMITED ON USERS;

CREATE TABLE safy_seed_owner.customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  tier VARCHAR2(20) NOT NULL
);

CREATE TABLE safy_seed_owner.orders (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER REFERENCES safy_seed_owner.customers(customer_id),
  total_amount NUMBER(10, 2) NOT NULL
);

INSERT INTO safy_seed_owner.customers (name, tier) VALUES ('Alice', 'gold');
INSERT INTO safy_seed_owner.customers (name, tier) VALUES ('Bob', 'silver');
INSERT INTO safy_seed_owner.orders (customer_id, total_amount) VALUES (1, 42.50);
INSERT INTO safy_seed_owner.orders (customer_id, total_amount) VALUES (2, 19.99);
COMMIT;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER safy_readonly IDENTIFIED BY "safy_ro_database_services_fake_123"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/
GRANT CREATE SESSION TO safy_readonly;
GRANT SELECT ON safy_seed_owner.customers TO safy_readonly;
GRANT SELECT ON safy_seed_owner.orders TO safy_readonly;
